# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etergrams', '0003_entry_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
