# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etergrams', '0004_auto_20170530_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
